package com.sct.service.database.mapper;

import com.sct.service.database.condition.QPaging;
import com.sct.service.database.condition.ScCommunityCondition;
import com.sct.service.database.entity.ScCommunity;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface ScCommunityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScCommunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    ScCommunity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScCommunity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int updateByPrimaryKey(ScCommunity record);

    int deleteByPrimaryKeys(@Param("ids") List<Integer> ids);

    int selectConditionCount(@Param("condition") ScCommunityCondition condition);

    List<ScCommunity> selectConditionPage(@Param("condition") ScCommunityCondition condition, @Param("qPaging") QPaging qPaging);

    List<ScCommunity> selectCondition(@Param("condition") ScCommunityCondition condition);

    List<Map<Integer, String>> getIdNameMapping();
}