package com.sct.service.database.mapper;

import com.sct.service.database.condition.QPaging;
import com.sct.service.database.condition.ScCommunityPartyCondition;
import com.sct.service.database.entity.ScCommunityParty;
import com.sct.service.database.entity.ScUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScCommunityPartyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community_party
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community_party
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScCommunityParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community_party
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    ScCommunityParty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community_party
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScCommunityParty> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community_party
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int updateByPrimaryKey(ScCommunityParty record);

    public int selectConditionCount(@Param("condition") ScCommunityPartyCondition condition);

    public List<ScUser> selectConditionPage(@Param("condition") ScCommunityPartyCondition condition, @Param("qPaging") QPaging qPaging);

    public List<ScUser> selectCondition(@Param("condition") ScCommunityPartyCondition condition);
}