package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScCommunity;
import java.util.List;

public interface ScCommunityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community
     *
     * @mbg.generated Sat Jan 02 12:33:41 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community
     *
     * @mbg.generated Sat Jan 02 12:33:41 CST 2021
     */
    int insert(ScCommunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community
     *
     * @mbg.generated Sat Jan 02 12:33:41 CST 2021
     */
    ScCommunity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community
     *
     * @mbg.generated Sat Jan 02 12:33:41 CST 2021
     */
    List<ScCommunity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community
     *
     * @mbg.generated Sat Jan 02 12:33:41 CST 2021
     */
    int updateByPrimaryKey(ScCommunity record);
}