package com.sct.service.database.mapper;

import com.sct.service.database.condition.QPaging;
import com.sct.service.database.condition.ScCommunityCondition;
import com.sct.service.database.entity.ScCommunity;
import com.sct.service.database.entity.ScUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScCommunityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScCommunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    ScCommunity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScCommunity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_community
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int updateByPrimaryKey(ScCommunity record);

    public int selectConditionCount(@Param("condition") ScCommunityCondition condition);

    public List<ScUser> selectConditionPage(@Param("condition") ScCommunityCondition condition, @Param("qPaging") QPaging qPaging);

    public List<ScUser> selectCondition(@Param("condition") ScCommunityCondition condition);
}