package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScDepartment;
import java.util.List;

public interface ScDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_department
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_department
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int insert(ScDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_department
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    ScDepartment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_department
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    List<ScDepartment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_department
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int updateByPrimaryKey(ScDepartment record);
}