package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScDict;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_dict
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int deleteByPrimaryKey(@Param("fieldId") String fieldId, @Param("dictId") Integer dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_dict
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int insert(ScDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_dict
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    ScDict selectByPrimaryKey(@Param("fieldId") String fieldId, @Param("dictId") Integer dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_dict
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    List<ScDict> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_dict
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int updateByPrimaryKey(ScDict record);
}