package com.sct.service.database.mapper;

import com.sct.service.database.condition.QPaging;
import com.sct.service.database.condition.ScEstateCondition;
import com.sct.service.database.entity.ScEstate;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScEstateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_estate
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_estate
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScEstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_estate
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    ScEstate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_estate
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScEstate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_estate
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int updateByPrimaryKey(ScEstate record);

    int deleteByPrimaryKeys(@Param("ids") List<Integer> ids);

    int selectConditionCount(@Param("condition") ScEstateCondition condition);

    List<ScEstate> selectConditionPage(@Param("condition") ScEstateCondition condition, @Param("qPaging") QPaging qPaging);

    List<ScEstate> selectCondition(@Param("condition") ScEstateCondition condition);

    List selectByCommunityId(@Param("communityId") Integer communityId);
}