package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScGrid;
import java.util.List;

public interface ScGridMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int insert(ScGrid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    ScGrid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    List<ScGrid> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int updateByPrimaryKey(ScGrid record);
}