package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScGridRange;
import java.util.List;

public interface ScGridRangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid_range
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int insert(ScGridRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid_range
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    List<ScGridRange> selectAll();
}