package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScGridEvaluation;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScGridEvaluationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid_evaluation
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(@Param("gridId") Integer gridId, @Param("gridManagerId") Integer gridManagerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid_evaluation
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScGridEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid_evaluation
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    ScGridEvaluation selectByPrimaryKey(@Param("gridId") Integer gridId, @Param("gridManagerId") Integer gridManagerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid_evaluation
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScGridEvaluation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid_evaluation
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int updateByPrimaryKey(ScGridEvaluation record);
}