package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScGrid;

import java.util.List;

public interface ScGridMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    int insert(ScGrid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    ScGrid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    List<ScGrid> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_grid
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    int updateByPrimaryKey(ScGrid record);
}