package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScHouse;

import java.util.List;

public interface ScHouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_house
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_house
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_house
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    ScHouse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_house
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScHouse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_house
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int updateByPrimaryKey(ScHouse record);
}