package com.sct.service.database.mapper;

import com.sct.service.database.condition.QPaging;
import com.sct.service.database.condition.ScLogCondition;
import com.sct.service.database.entity.ScLog;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_log
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_log
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_log
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    ScLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_log
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_log
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int updateByPrimaryKey(ScLog record);

    public int selectConditionCount(@Param("condition") ScLogCondition condition);

    public List<ScLog> selectConditionPage(@Param("condition") ScLogCondition condition, @Param("qPaging") QPaging qPaging);

    public List<ScLog> selectCondition(@Param("condition") ScLogCondition condition);
}