package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScOrganization;
import java.util.List;

public interface ScOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_organization
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_organization
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int insert(ScOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_organization
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    ScOrganization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_organization
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    List<ScOrganization> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_organization
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int updateByPrimaryKey(ScOrganization record);
}