package com.sct.service.database.mapper;

import com.sct.service.database.condition.QPaging;
import com.sct.service.database.condition.ScPartyMemberRecordCondition;
import com.sct.service.database.entity.ScPartyMember;
import com.sct.service.database.entity.ScPartyMemberRecord;
import com.sct.service.database.entity.ScPartySpecialDues;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface ScPartyMemberRecordMapper {
    int deleteByPrimaryKey(Integer id);

    int deleteByPrimaryKeys(@Param("ids") List<Integer> ids);

    int deleteByBusinessKey(@Param("partyMemberId") Integer partyMemberId, @Param("recordDate") Date recordDate);

    ScPartyMemberRecord selectDocumentary(@Param("id") Integer id);

    List<ScPartyMemberRecord> selectDocumentaryAll(@Param("partyMemberId") Integer partyMemberId,@Param("recordType") Integer recordType);

    int updateByPrimaryKey(ScPartyMemberRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_member_record
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScPartyMemberRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_member_record
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScPartyMemberRecord> selectAll();

    public int selectConditionCount(@Param("condition") ScPartyMemberRecordCondition condition);

    public List<ScPartyMemberRecord> selectConditionPage(@Param("condition") ScPartyMemberRecordCondition condition, @Param("qPaging") QPaging qPaging);

    public List<ScPartyMemberRecord> selectCondition(@Param("condition") ScPartyMemberRecordCondition condition);
}