package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScPartyLearnFiles;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScPartyLearnFilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_learn_files
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("activityId") Integer activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_learn_files
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScPartyLearnFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_learn_files
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    ScPartyLearnFiles selectByPrimaryKey(@Param("id") Integer id, @Param("activityId") Integer activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_learn_files
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScPartyLearnFiles> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_learn_files
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int updateByPrimaryKey(ScPartyLearnFiles record);
}