package com.sct.service.database.mapper;

import com.sct.service.database.condition.QPaging;
import com.sct.service.database.condition.ScPartyMemberCondition;
import com.sct.service.database.entity.ScPartyMember;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScPartyMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_member
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    int deleteByPrimaryKeys(@Param("ids") List<Integer> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_member
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScPartyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_member
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    ScPartyMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_member
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScPartyMember> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_member
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int updateByPrimaryKey(ScPartyMember record);

    public int selectConditionCount(@Param("condition") ScPartyMemberCondition condition);

    public List<ScPartyMember> selectConditionPage(@Param("condition") ScPartyMemberCondition condition, @Param("qPaging") QPaging qPaging);

    public List<ScPartyMember> selectCondition(@Param("condition") ScPartyMemberCondition condition);
}