package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScPartyDues;

import java.util.List;

public interface ScPartyDuesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_dues
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScPartyDues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_dues
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScPartyDues> selectAll();
}