package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScPartyMember;
import com.sct.service.database.entity.ScPartySpecialDues;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface ScPartySpecialDuesMapper {
    int deleteByPrimaryKey(Integer id);

    int deleteByPrimaryKeys(@Param("ids") List<Integer> ids);

    int deleteByBusinessKey(@Param("partyMemberId") Integer partyMemberId, @Param("dueStage") Date dueStage, @Param("payDate") Date payDate);

    ScPartySpecialDues selectDocumentary(@Param("id") Integer id);

    List<ScPartySpecialDues> selectDocumentaryAll(@Param("partyMemberId") Integer partyMemberId);

    int updateByPrimaryKey(ScPartyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_special_dues
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScPartySpecialDues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_special_dues
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScPartySpecialDues> selectAll();
}