package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScPartySpecialDues;

import java.util.List;

public interface ScPartySpecialDuesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_special_dues
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScPartySpecialDues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_special_dues
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScPartySpecialDues> selectAll();
}