package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScPartyLearnRecord;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScPartyLearnRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_learn_record
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(@Param("partyMemberId") Integer partyMemberId, @Param("courseId") Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_learn_record
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScPartyLearnRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_learn_record
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    ScPartyLearnRecord selectByPrimaryKey(@Param("partyMemberId") Integer partyMemberId, @Param("courseId") Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_learn_record
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScPartyLearnRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_learn_record
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int updateByPrimaryKey(ScPartyLearnRecord record);
}