package com.sct.service.database.mapper;

import com.sct.service.database.condition.QPaging;
import com.sct.service.database.condition.ScPartyActivitiesCondition;
import com.sct.service.database.entity.ScOrganization;
import com.sct.service.database.entity.ScPartyActivities;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScPartyActivitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_activities
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(@Param("id") Integer id);

    int deleteByPrimaryKeys(@Param("ids") List<Integer> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_activities
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScPartyActivities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_activities
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    ScPartyActivities selectByPrimaryKey(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_activities
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScPartyActivities> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_activities
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int updateByPrimaryKey(ScPartyActivities record);

    public int selectConditionCount(@Param("condition") ScPartyActivitiesCondition condition);

    public List<ScOrganization> selectConditionPage(@Param("condition") ScPartyActivitiesCondition condition, @Param("qPaging") QPaging qPaging);

    public List<ScOrganization> selectCondition(@Param("condition") ScPartyActivitiesCondition condition);

}