package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScPartyDues;
import com.sct.service.database.entity.ScPartyMemberRecord;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface ScPartyDuesMapper {
    int deleteByPrimaryKey(Integer id);

    int deleteByPrimaryKeys(@Param("ids") List<Integer> ids);

    int deleteByBusinessKey(@Param("partyMemberId") Integer partyMemberId, @Param("dueStage") Date dueStage, @Param("payDate") Date payDate);

    ScPartyDues selectDocumentary(@Param("id") Integer id);

    List<ScPartyDues> selectDocumentaryAll(@Param("partyMemberId") Integer partyMemberId);

    int updateByPrimaryKey(ScPartyDues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_dues
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScPartyDues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_dues
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScPartyDues> selectAll();
}