package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScPartyCourse;

import java.util.List;

public interface ScPartyCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_course
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_course
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScPartyCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_course
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    ScPartyCourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_course
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScPartyCourse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_party_course
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int updateByPrimaryKey(ScPartyCourse record);
}