package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScPropertyStaff;
import java.util.List;

public interface ScPropertyStaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_property_staff
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_property_staff
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int insert(ScPropertyStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_property_staff
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    ScPropertyStaff selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_property_staff
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    List<ScPropertyStaff> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_property_staff
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int updateByPrimaryKey(ScPropertyStaff record);
}