package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScProperty;
import java.util.List;

public interface ScPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_property
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_property
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int insert(ScProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_property
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    ScProperty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_property
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    List<ScProperty> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_property
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int updateByPrimaryKey(ScProperty record);
}