package com.sct.service.database.mapper;

import com.sct.service.database.condition.QPaging;
import com.sct.service.database.condition.ScResidentCondition;
import com.sct.service.database.condition.ScResidentCondition;
import com.sct.service.database.entity.ScResident;
import com.sct.service.database.entity.ScResident;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScResidentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_resident
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_resident
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScResident record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_resident
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    ScResident selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_resident
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScResident> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_resident
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int updateByPrimaryKey(ScResident record);


    ScResident selectByCardId(String cardId);

    List<ScResident> searchScResident(@Param("condition") ScResidentCondition condition);

    int deleteByPrimaryKeys(@Param("ids") List<Integer> ids);

    int selectConditionCount(@Param("condition") ScResidentCondition condition);

    List<ScResident> selectConditionPage(@Param("condition") ScResidentCondition condition, @Param("qPaging") QPaging qPaging);

    List<ScResident> selectCondition(@Param("condition") ScResidentCondition condition);
}