package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScRoleDatas;

import java.util.List;

public interface ScRoleDatasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role_datas
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScRoleDatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role_datas
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScRoleDatas> selectAll();
}