package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScRoleOperations;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScRoleOperationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role_operations
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(@Param("roleId") Integer roleId, @Param("devType") Integer devType, @Param("operId") Integer operId);

    int deleteByPrimaryKeyCondition(@Param("roleId") Integer roleId, @Param("devType") Integer devType, @Param("operId") Integer operId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role_operations
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScRoleOperations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role_operations
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScRoleOperations> selectAll();
}