package com.sct.service.database.mapper;

import com.sct.service.database.condition.QPaging;
import com.sct.service.database.condition.ScRoleCondition;
import com.sct.service.database.entity.ScRole;
import com.sct.service.database.entity.ScUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    ScRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int updateByPrimaryKey(ScRole record);

    public int selectConditionCount(@Param("condition") ScRoleCondition condition);

    public List<ScUser> selectConditionPage(@Param("condition") ScRoleCondition condition, @Param("qPaging") QPaging qPaging);

    public List<ScUser> selectCondition(@Param("condition") ScRoleCondition condition);
}