package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScRole;
import java.util.List;

public interface ScRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int insert(ScRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    ScRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    List<ScRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int updateByPrimaryKey(ScRole record);
}