package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScRoleDatas;

import java.util.List;

public interface ScRoleDatasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role_datas
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    int insert(ScRoleDatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_role_datas
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    List<ScRoleDatas> selectAll();
}