package com.sct.service.database.mapper;

import com.sct.service.database.condition.QPaging;
import com.sct.service.database.condition.ScSsoLogCondition;
import com.sct.service.database.entity.ScSsoLog;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScSsoLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_sso_log
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_sso_log
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    int insert(ScSsoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_sso_log
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    ScSsoLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_sso_log
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    List<ScSsoLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_sso_log
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    int updateByPrimaryKey(ScSsoLog record);

    public int selectConditionCount(@Param("condition") ScSsoLogCondition condition);

    public List<ScSsoLog> selectConditionPage(@Param("condition") ScSsoLogCondition condition, @Param("qPaging") QPaging qPaging);

    public List<ScSsoLog> selectCondition(@Param("condition") ScSsoLogCondition condition);
}