package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScUserHouseRelHis;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScUserHouseRelHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_house_rel_his
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("houseId") Integer houseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_house_rel_his
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int insert(ScUserHouseRelHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_house_rel_his
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    ScUserHouseRelHis selectByPrimaryKey(@Param("userId") Integer userId, @Param("houseId") Integer houseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_house_rel_his
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    List<ScUserHouseRelHis> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_house_rel_his
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int updateByPrimaryKey(ScUserHouseRelHis record);
}