package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScUser;

import java.util.List;

public interface ScUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    int insert(ScUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    ScUser selectByPrimaryKey(String id);

    ScUser selectByLoginId(String value);

    ScUser selectByMobile(String value);

    ScUser selectByEmail(String value);

    ScUser selectBywxid(String value);

    ScUser selectByMixed(String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    List<ScUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    int updateByPrimaryKey(ScUser record);
}