package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScUserRoleRel;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScUserRoleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_role_rel
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("roleId") Integer roleId, @Param("roleType") Boolean roleType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_role_rel
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int insert(ScUserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_role_rel
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    List<ScUserRoleRel> selectAll();
}