package com.sct.service.database.mapper;

import com.sct.service.database.condition.QPaging;
import com.sct.service.database.condition.ScUserCondition;
import com.sct.service.database.entity.ScUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    int deleteByPrimaryKeys(@Param("ids") List<Integer> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int insert(ScUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    ScUser selectByPrimaryKey(Integer id);

    ScUser selectByLoginId(String value);

    ScUser selectByMobile(String value);

    ScUser selectByEmail(String value);

    ScUser selectBywxid(String value);

    ScUser selectByCardId(String value);

    ScUser selectByMixed(String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    List<ScUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    int updateByPrimaryKey(ScUser record);

    /**
     * 更新密码
     *
     * @param id
     * @param password
     * @return
     */
    int updatePasswordById(@Param("id") Integer id, @Param("password") String password);

    /**
     * 更新状态
     *
     * @param id
     * @param valid
     * @return
     */
    int updateIsValidById(@Param("id") Integer id, @Param("valid") Integer valid);

    public int selectConditionCount(@Param("condition") ScUserCondition condition);

    public List<ScUser> selectConditionPage(@Param("condition") ScUserCondition condition, @Param("qPaging") QPaging qPaging);

    public List<ScUser> selectCondition(@Param("condition") ScUserCondition condition);
}