package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScUserRole;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_role
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    int deleteByPrimaryKey(@Param("userId") String userId, @Param("roleId") Integer roleId, @Param("roleType") Boolean roleType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_role
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    int insert(ScUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_role
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    List<ScUserRole> selectAll();
}