package com.sct.service.database.mapper;

import com.sct.service.database.entity.ScZone;
import java.util.List;

public interface ScZoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_zone
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    int insert(ScZone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_zone
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    List<ScZone> selectAll();
}