server:
  servlet:
    session:
      timeout: PT12H
  compression:
    enabled: true
    min-response-size: 1024

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG

security:
  jwk-set-uri: http://localhost:8090/auth/realms/oauth2-sample/protocol/openid-connect/certs
datasource:
  jdbc:
    url: jdbc:mysql://192.168.1.21:3306/irdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: irsoft
    password: irsoft
    driver: com.mysql.cj.jdbc.Driver
    max-active: 20
    validation-query: SELECT 1

spring:
  application: application-business
  messages:
    basename: i18n/sct_messages
  datasource:
    url: ${datasource.jdbc.url}
    username: ${datasource.jdbc.username}
    password: ${datasource.jdbc.password}
    driver-class-name: ${datasource.jdbc.driver}
    max-active: ${datasource.jdbc.max-active}
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: ${datasource.jdbc.validation-query}
    time-between-eviction-runs-millis: 18800
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=50)
    type: com.alibaba.druid.pool.DruidDataSource
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${security.jwk-set-uri}

mybatis:
  config-location: classpath:config/mybatis-base-config.xml
  mapper-locations: classpath:mapper/*.xml
  scanner:
    enable: true
    base-package: com.sct.service.database.mapper
  factor:
    enable: false
    config-location: classpath:config/mybatis-base-config.xml
    mapper-locations: classpath:mapper/*.xml
