server:
  servlet:
    session:
      timeout: PT12H
  compression:
    enabled: true
    min-response-size: 1024

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG

security:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    max-active: 20
    validation-query: SELECT 1
  oauth2:
    resource:
      jwk:
        key-set-uri: ${security.jwk-set-uri}

spring:
  application: application-summary
  messages:
    basename: i18n/sct_messages,i18n/sct_messages_users,i18n/screen-message,i18n/sct_messages_exception
  datasource:
    url: ${security.datasource.url}
    username: ${security.datasource.username}
    password: ${security.datasource.password}
    driver-class-name: ${security.datasource.driver}
    max-active: ${security.datasource.max-active}
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: ${security.datasource.validation-query}
    time-between-eviction-runs-millis: 18800
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=50)
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  config-location: classpath:config/mybatis-base-config.xml
  mapper-locations: classpath:mapper/*.xml
  scanner:
    enable: true
    base-package: com.sct.service.database.mapper
  factor:
    enable: false
    config-location: classpath:config/mybatis-base-config.xml
    mapper-locations: classpath:mapper/*.xml
