package com.sct.service.database.entity;

import com.sct.service.database.extend.ScGridBuildingExtendDisplay;

import java.io.Serializable;
import java.util.Date;

public class ScBuilding extends ScGridBuildingExtendDisplay implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.estate_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer estateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.community_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.grid_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer gridId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.building_type
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer buildingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.address
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.completed_date
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date completedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.floor_count
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer floorCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.unit_count
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer unitCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.comment
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.marker_status
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer markerStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.latitude
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Float latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.longitude
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Float longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_building.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_building
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.id
     *
     * @return the value of sc_building.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.id
     *
     * @param id the value for sc_building.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.name
     *
     * @return the value of sc_building.name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.name
     *
     * @param name the value for sc_building.name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.estate_id
     *
     * @return the value of sc_building.estate_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getEstateId() {
        return estateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.estate_id
     *
     * @param estateId the value for sc_building.estate_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setEstateId(Integer estateId) {
        this.estateId = estateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.community_id
     *
     * @return the value of sc_building.community_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.community_id
     *
     * @param communityId the value for sc_building.community_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.grid_id
     *
     * @return the value of sc_building.grid_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getGridId() {
        return gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.grid_id
     *
     * @param gridId the value for sc_building.grid_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setGridId(Integer gridId) {
        this.gridId = gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.building_type
     *
     * @return the value of sc_building.building_type
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getBuildingType() {
        return buildingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.building_type
     *
     * @param buildingType the value for sc_building.building_type
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setBuildingType(Integer buildingType) {
        this.buildingType = buildingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.address
     *
     * @return the value of sc_building.address
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.address
     *
     * @param address the value for sc_building.address
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.completed_date
     *
     * @return the value of sc_building.completed_date
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getCompletedDate() {
        return completedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.completed_date
     *
     * @param completedDate the value for sc_building.completed_date
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCompletedDate(Date completedDate) {
        this.completedDate = completedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.floor_count
     *
     * @return the value of sc_building.floor_count
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getFloorCount() {
        return floorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.floor_count
     *
     * @param floorCount the value for sc_building.floor_count
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setFloorCount(Integer floorCount) {
        this.floorCount = floorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.unit_count
     *
     * @return the value of sc_building.unit_count
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getUnitCount() {
        return unitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.unit_count
     *
     * @param unitCount the value for sc_building.unit_count
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setUnitCount(Integer unitCount) {
        this.unitCount = unitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.comment
     *
     * @return the value of sc_building.comment
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.comment
     *
     * @param comment the value for sc_building.comment
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.marker_status
     *
     * @return the value of sc_building.marker_status
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getMarkerStatus() {
        return markerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.marker_status
     *
     * @param markerStatus the value for sc_building.marker_status
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setMarkerStatus(Integer markerStatus) {
        this.markerStatus = markerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.latitude
     *
     * @return the value of sc_building.latitude
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.latitude
     *
     * @param latitude the value for sc_building.latitude
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.longitude
     *
     * @return the value of sc_building.longitude
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.longitude
     *
     * @param longitude the value for sc_building.longitude
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.create_time
     *
     * @return the value of sc_building.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.create_time
     *
     * @param createTime the value for sc_building.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.creator_id
     *
     * @return the value of sc_building.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.creator_id
     *
     * @param creatorId the value for sc_building.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_building.modify_time
     *
     * @return the value of sc_building.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_building.modify_time
     *
     * @param modifyTime the value for sc_building.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}