package com.sct.service.database.entity;

import java.io.Serializable;
import java.util.Date;

public class ScDepartment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_department.id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_department.name
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_department.create_time
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_department.creator_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_department.modify_time
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_department
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_department.id
     *
     * @return the value of sc_department.id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_department.id
     *
     * @param id the value for sc_department.id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_department.name
     *
     * @return the value of sc_department.name
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_department.name
     *
     * @param name the value for sc_department.name
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_department.create_time
     *
     * @return the value of sc_department.create_time
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_department.create_time
     *
     * @param createTime the value for sc_department.create_time
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_department.creator_id
     *
     * @return the value of sc_department.creator_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_department.creator_id
     *
     * @param creatorId the value for sc_department.creator_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_department.modify_time
     *
     * @return the value of sc_department.modify_time
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_department.modify_time
     *
     * @param modifyTime the value for sc_department.modify_time
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}