package com.sct.service.database.entity;

import com.sct.service.database.extend.BaseExtend;

import java.io.Serializable;
import java.util.Date;

public class ScEstateStaffRel extends BaseExtend implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_estate_staff_rel.estate_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer estateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_estate_staff_rel.staff_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_estate_staff_rel.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_estate_staff_rel.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_estate_staff_rel.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_estate_staff_rel
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_estate_staff_rel.estate_id
     *
     * @return the value of sc_estate_staff_rel.estate_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getEstateId() {
        return estateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_estate_staff_rel.estate_id
     *
     * @param estateId the value for sc_estate_staff_rel.estate_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setEstateId(Integer estateId) {
        this.estateId = estateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_estate_staff_rel.staff_id
     *
     * @return the value of sc_estate_staff_rel.staff_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_estate_staff_rel.staff_id
     *
     * @param staffId the value for sc_estate_staff_rel.staff_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_estate_staff_rel.create_time
     *
     * @return the value of sc_estate_staff_rel.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_estate_staff_rel.create_time
     *
     * @param createTime the value for sc_estate_staff_rel.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_estate_staff_rel.creator_id
     *
     * @return the value of sc_estate_staff_rel.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_estate_staff_rel.creator_id
     *
     * @param creatorId the value for sc_estate_staff_rel.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_estate_staff_rel.modify_time
     *
     * @return the value of sc_estate_staff_rel.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_estate_staff_rel.modify_time
     *
     * @param modifyTime the value for sc_estate_staff_rel.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}