package com.sct.service.database.entity;

import java.io.Serializable;
import java.util.Date;

public class ScEstate implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_estate.id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_estate.name
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_estate.coverd_area
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private Float coverdArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_estate.property_id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private Integer propertyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_estate.property_fee
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private Float propertyFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_estate.comment
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_estate.community_id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private Integer communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_estate.create_time
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_estate.creator_id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_estate.modify_time
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_estate
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_estate.id
     *
     * @return the value of sc_estate.id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_estate.id
     *
     * @param id the value for sc_estate.id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_estate.name
     *
     * @return the value of sc_estate.name
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_estate.name
     *
     * @param name the value for sc_estate.name
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_estate.coverd_area
     *
     * @return the value of sc_estate.coverd_area
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public Float getCoverdArea() {
        return coverdArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_estate.coverd_area
     *
     * @param coverdArea the value for sc_estate.coverd_area
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setCoverdArea(Float coverdArea) {
        this.coverdArea = coverdArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_estate.property_id
     *
     * @return the value of sc_estate.property_id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public Integer getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_estate.property_id
     *
     * @param propertyId the value for sc_estate.property_id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_estate.property_fee
     *
     * @return the value of sc_estate.property_fee
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public Float getPropertyFee() {
        return propertyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_estate.property_fee
     *
     * @param propertyFee the value for sc_estate.property_fee
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setPropertyFee(Float propertyFee) {
        this.propertyFee = propertyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_estate.comment
     *
     * @return the value of sc_estate.comment
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_estate.comment
     *
     * @param comment the value for sc_estate.comment
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_estate.community_id
     *
     * @return the value of sc_estate.community_id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_estate.community_id
     *
     * @param communityId the value for sc_estate.community_id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_estate.create_time
     *
     * @return the value of sc_estate.create_time
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_estate.create_time
     *
     * @param createTime the value for sc_estate.create_time
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_estate.creator_id
     *
     * @return the value of sc_estate.creator_id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_estate.creator_id
     *
     * @param creatorId the value for sc_estate.creator_id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_estate.modify_time
     *
     * @return the value of sc_estate.modify_time
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_estate.modify_time
     *
     * @param modifyTime the value for sc_estate.modify_time
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}