package com.sct.service.database.entity;

import com.sct.service.database.extend.ScGridManagerExtendDisplay;

import java.io.Serializable;
import java.util.Date;

public class ScGridManager extends ScGridManagerExtendDisplay implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_grid_manager.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_grid_manager.name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_grid_manager.grid_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer gridId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_grid_manager.mobile
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_grid_manager.pic_url
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_grid_manager.employ_date
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date employDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_grid_manager.leave_date
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date leaveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_grid_manager.leave_reason
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String leaveReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_grid_manager.is_leader
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer isLeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_grid_manager.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_grid_manager.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_grid_manager.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_grid_manager
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_grid_manager.id
     *
     * @return the value of sc_grid_manager.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_grid_manager.id
     *
     * @param id the value for sc_grid_manager.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_grid_manager.name
     *
     * @return the value of sc_grid_manager.name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_grid_manager.name
     *
     * @param name the value for sc_grid_manager.name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_grid_manager.grid_id
     *
     * @return the value of sc_grid_manager.grid_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getGridId() {
        return gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_grid_manager.grid_id
     *
     * @param gridId the value for sc_grid_manager.grid_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setGridId(Integer gridId) {
        this.gridId = gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_grid_manager.mobile
     *
     * @return the value of sc_grid_manager.mobile
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_grid_manager.mobile
     *
     * @param mobile the value for sc_grid_manager.mobile
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_grid_manager.pic_url
     *
     * @return the value of sc_grid_manager.pic_url
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_grid_manager.pic_url
     *
     * @param picUrl the value for sc_grid_manager.pic_url
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_grid_manager.employ_date
     *
     * @return the value of sc_grid_manager.employ_date
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getEmployDate() {
        return employDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_grid_manager.employ_date
     *
     * @param employDate the value for sc_grid_manager.employ_date
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setEmployDate(Date employDate) {
        this.employDate = employDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_grid_manager.leave_date
     *
     * @return the value of sc_grid_manager.leave_date
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getLeaveDate() {
        return leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_grid_manager.leave_date
     *
     * @param leaveDate the value for sc_grid_manager.leave_date
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_grid_manager.leave_reason
     *
     * @return the value of sc_grid_manager.leave_reason
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getLeaveReason() {
        return leaveReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_grid_manager.leave_reason
     *
     * @param leaveReason the value for sc_grid_manager.leave_reason
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setLeaveReason(String leaveReason) {
        this.leaveReason = leaveReason == null ? null : leaveReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_grid_manager.is_leader
     *
     * @return the value of sc_grid_manager.is_leader
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getIsLeader() {
        return isLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_grid_manager.is_leader
     *
     * @param isLeader the value for sc_grid_manager.is_leader
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setIsLeader(Integer isLeader) {
        this.isLeader = isLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_grid_manager.create_time
     *
     * @return the value of sc_grid_manager.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_grid_manager.create_time
     *
     * @param createTime the value for sc_grid_manager.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_grid_manager.creator_id
     *
     * @return the value of sc_grid_manager.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_grid_manager.creator_id
     *
     * @param creatorId the value for sc_grid_manager.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_grid_manager.modify_time
     *
     * @return the value of sc_grid_manager.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_grid_manager.modify_time
     *
     * @param modifyTime the value for sc_grid_manager.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}