package com.sct.service.database.entity;

import com.sct.service.database.extend.BaseExtend;
import com.sct.service.database.extend.ScGridHouseExtendDisplay;

import java.io.Serializable;
import java.util.Date;

public class ScHouse extends ScGridHouseExtendDisplay implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_house.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_house.room_numer
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer roomNumer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_house.unit
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_house.floor
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_house.building_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer buildingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_house.owner_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_house.house_status
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer houseStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_house.house_attribute
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer houseAttribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_house.area
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Float area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_house.comment
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_house.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_house.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_house.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_house
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_house.id
     *
     * @return the value of sc_house.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_house.id
     *
     * @param id the value for sc_house.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_house.room_numer
     *
     * @return the value of sc_house.room_numer
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getRoomNumer() {
        return roomNumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_house.room_numer
     *
     * @param roomNumer the value for sc_house.room_numer
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setRoomNumer(Integer roomNumer) {
        this.roomNumer = roomNumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_house.unit
     *
     * @return the value of sc_house.unit
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_house.unit
     *
     * @param unit the value for sc_house.unit
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_house.floor
     *
     * @return the value of sc_house.floor
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_house.floor
     *
     * @param floor the value for sc_house.floor
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_house.building_id
     *
     * @return the value of sc_house.building_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_house.building_id
     *
     * @param buildingId the value for sc_house.building_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setBuildingId(Integer buildingId) {
        this.buildingId = buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_house.owner_id
     *
     * @return the value of sc_house.owner_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_house.owner_id
     *
     * @param ownerId the value for sc_house.owner_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_house.house_status
     *
     * @return the value of sc_house.house_status
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getHouseStatus() {
        return houseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_house.house_status
     *
     * @param houseStatus the value for sc_house.house_status
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setHouseStatus(Integer houseStatus) {
        this.houseStatus = houseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_house.house_attribute
     *
     * @return the value of sc_house.house_attribute
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getHouseAttribute() {
        return houseAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_house.house_attribute
     *
     * @param houseAttribute the value for sc_house.house_attribute
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setHouseAttribute(Integer houseAttribute) {
        this.houseAttribute = houseAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_house.area
     *
     * @return the value of sc_house.area
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Float getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_house.area
     *
     * @param area the value for sc_house.area
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setArea(Float area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_house.comment
     *
     * @return the value of sc_house.comment
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_house.comment
     *
     * @param comment the value for sc_house.comment
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_house.create_time
     *
     * @return the value of sc_house.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_house.create_time
     *
     * @param createTime the value for sc_house.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_house.creator_id
     *
     * @return the value of sc_house.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_house.creator_id
     *
     * @param creatorId the value for sc_house.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_house.modify_time
     *
     * @return the value of sc_house.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_house.modify_time
     *
     * @param modifyTime the value for sc_house.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}