package com.sct.service.database.entity;

import com.sct.service.database.extend.BaseExtend;

import java.io.Serializable;
import java.util.Date;

public class ScPartyMember extends BaseExtend implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.party_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer partyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.community_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.sex
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.nation
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.card_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.political_status
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer politicalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.party_member_type
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer partyMemberType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.party_post
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer partyPost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.admin_post
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String adminPost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.birthday
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.join_date
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date joinDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.pic_url
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.qualifications
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer qualifications;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.marry_status
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer marryStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.mobile
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.settle_address
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String settleAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.comment
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_member.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_party_member
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.id
     *
     * @return the value of sc_party_member.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.id
     *
     * @param id the value for sc_party_member.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.name
     *
     * @return the value of sc_party_member.name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.name
     *
     * @param name the value for sc_party_member.name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.party_id
     *
     * @return the value of sc_party_member.party_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getPartyId() {
        return partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.party_id
     *
     * @param partyId the value for sc_party_member.party_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setPartyId(Integer partyId) {
        this.partyId = partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.community_id
     *
     * @return the value of sc_party_member.community_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.community_id
     *
     * @param communityId the value for sc_party_member.community_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.sex
     *
     * @return the value of sc_party_member.sex
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.sex
     *
     * @param sex the value for sc_party_member.sex
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.nation
     *
     * @return the value of sc_party_member.nation
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.nation
     *
     * @param nation the value for sc_party_member.nation
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setNation(Integer nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.card_id
     *
     * @return the value of sc_party_member.card_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.card_id
     *
     * @param cardId the value for sc_party_member.card_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.political_status
     *
     * @return the value of sc_party_member.political_status
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getPoliticalStatus() {
        return politicalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.political_status
     *
     * @param politicalStatus the value for sc_party_member.political_status
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setPoliticalStatus(Integer politicalStatus) {
        this.politicalStatus = politicalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.party_member_type
     *
     * @return the value of sc_party_member.party_member_type
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getPartyMemberType() {
        return partyMemberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.party_member_type
     *
     * @param partyMemberType the value for sc_party_member.party_member_type
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setPartyMemberType(Integer partyMemberType) {
        this.partyMemberType = partyMemberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.party_post
     *
     * @return the value of sc_party_member.party_post
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getPartyPost() {
        return partyPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.party_post
     *
     * @param partyPost the value for sc_party_member.party_post
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setPartyPost(Integer partyPost) {
        this.partyPost = partyPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.admin_post
     *
     * @return the value of sc_party_member.admin_post
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getAdminPost() {
        return adminPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.admin_post
     *
     * @param adminPost the value for sc_party_member.admin_post
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setAdminPost(String adminPost) {
        this.adminPost = adminPost == null ? null : adminPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.birthday
     *
     * @return the value of sc_party_member.birthday
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.birthday
     *
     * @param birthday the value for sc_party_member.birthday
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.join_date
     *
     * @return the value of sc_party_member.join_date
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.join_date
     *
     * @param joinDate the value for sc_party_member.join_date
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.pic_url
     *
     * @return the value of sc_party_member.pic_url
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.pic_url
     *
     * @param picUrl the value for sc_party_member.pic_url
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.qualifications
     *
     * @return the value of sc_party_member.qualifications
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getQualifications() {
        return qualifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.qualifications
     *
     * @param qualifications the value for sc_party_member.qualifications
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setQualifications(Integer qualifications) {
        this.qualifications = qualifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.marry_status
     *
     * @return the value of sc_party_member.marry_status
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getMarryStatus() {
        return marryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.marry_status
     *
     * @param marryStatus the value for sc_party_member.marry_status
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setMarryStatus(Integer marryStatus) {
        this.marryStatus = marryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.mobile
     *
     * @return the value of sc_party_member.mobile
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.mobile
     *
     * @param mobile the value for sc_party_member.mobile
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.settle_address
     *
     * @return the value of sc_party_member.settle_address
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getSettleAddress() {
        return settleAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.settle_address
     *
     * @param settleAddress the value for sc_party_member.settle_address
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setSettleAddress(String settleAddress) {
        this.settleAddress = settleAddress == null ? null : settleAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.comment
     *
     * @return the value of sc_party_member.comment
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.comment
     *
     * @param comment the value for sc_party_member.comment
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.create_time
     *
     * @return the value of sc_party_member.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.create_time
     *
     * @param createTime the value for sc_party_member.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.creator_id
     *
     * @return the value of sc_party_member.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.creator_id
     *
     * @param creatorId the value for sc_party_member.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_member.modify_time
     *
     * @return the value of sc_party_member.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_member.modify_time
     *
     * @param modifyTime the value for sc_party_member.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}