package com.sct.service.database.entity;

import com.sct.service.database.extend.BaseExtend;

import java.io.Serializable;
import java.util.Date;

public class ScPartyTopic extends BaseExtend implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_topic.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_topic.party_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer partyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_topic.logo
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_topic.description
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_topic.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_topic.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_party_topic.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_party_topic
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_topic.id
     *
     * @return the value of sc_party_topic.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_topic.id
     *
     * @param id the value for sc_party_topic.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_topic.party_id
     *
     * @return the value of sc_party_topic.party_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getPartyId() {
        return partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_topic.party_id
     *
     * @param partyId the value for sc_party_topic.party_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setPartyId(Integer partyId) {
        this.partyId = partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_topic.logo
     *
     * @return the value of sc_party_topic.logo
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_topic.logo
     *
     * @param logo the value for sc_party_topic.logo
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_topic.description
     *
     * @return the value of sc_party_topic.description
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_topic.description
     *
     * @param description the value for sc_party_topic.description
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_topic.create_time
     *
     * @return the value of sc_party_topic.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_topic.create_time
     *
     * @param createTime the value for sc_party_topic.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_topic.creator_id
     *
     * @return the value of sc_party_topic.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_topic.creator_id
     *
     * @param creatorId the value for sc_party_topic.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_party_topic.modify_time
     *
     * @return the value of sc_party_topic.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_party_topic.modify_time
     *
     * @param modifyTime the value for sc_party_topic.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}