package com.sct.service.database.entity;

import com.sct.service.database.extend.BaseExtend;

import java.io.Serializable;
import java.util.Date;

public class ScProperty extends BaseExtend implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property.id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property.name
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property.property_type
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private Integer propertyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property.leader_name
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private String leaderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property.mobile
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property.create_time
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property.creator_id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property.modify_time
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_property
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property.id
     *
     * @return the value of sc_property.id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property.id
     *
     * @param id the value for sc_property.id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property.name
     *
     * @return the value of sc_property.name
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property.name
     *
     * @param name the value for sc_property.name
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property.property_type
     *
     * @return the value of sc_property.property_type
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public Integer getPropertyType() {
        return propertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property.property_type
     *
     * @param propertyType the value for sc_property.property_type
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setPropertyType(Integer propertyType) {
        this.propertyType = propertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property.leader_name
     *
     * @return the value of sc_property.leader_name
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public String getLeaderName() {
        return leaderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property.leader_name
     *
     * @param leaderName the value for sc_property.leader_name
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setLeaderName(String leaderName) {
        this.leaderName = leaderName == null ? null : leaderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property.mobile
     *
     * @return the value of sc_property.mobile
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property.mobile
     *
     * @param mobile the value for sc_property.mobile
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property.create_time
     *
     * @return the value of sc_property.create_time
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property.create_time
     *
     * @param createTime the value for sc_property.create_time
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property.creator_id
     *
     * @return the value of sc_property.creator_id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property.creator_id
     *
     * @param creatorId the value for sc_property.creator_id
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property.modify_time
     *
     * @return the value of sc_property.modify_time
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property.modify_time
     *
     * @param modifyTime the value for sc_property.modify_time
     *
     * @mbg.generated Sat Jan 02 12:33:42 CST 2021
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}