package com.sct.service.database.entity;

import com.sct.service.database.extend.BaseExtend;

import java.io.Serializable;
import java.util.Date;

public class ScPropertyStaff extends BaseExtend implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property_staff.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property_staff.name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property_staff.mobile
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property_staff.pic_url
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property_staff.property_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer propertyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property_staff.staff_type
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer staffType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property_staff.duty
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property_staff.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property_staff.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_property_staff.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_property_staff
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property_staff.id
     *
     * @return the value of sc_property_staff.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property_staff.id
     *
     * @param id the value for sc_property_staff.id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property_staff.name
     *
     * @return the value of sc_property_staff.name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property_staff.name
     *
     * @param name the value for sc_property_staff.name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property_staff.mobile
     *
     * @return the value of sc_property_staff.mobile
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property_staff.mobile
     *
     * @param mobile the value for sc_property_staff.mobile
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property_staff.pic_url
     *
     * @return the value of sc_property_staff.pic_url
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property_staff.pic_url
     *
     * @param picUrl the value for sc_property_staff.pic_url
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property_staff.property_id
     *
     * @return the value of sc_property_staff.property_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property_staff.property_id
     *
     * @param propertyId the value for sc_property_staff.property_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property_staff.staff_type
     *
     * @return the value of sc_property_staff.staff_type
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getStaffType() {
        return staffType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property_staff.staff_type
     *
     * @param staffType the value for sc_property_staff.staff_type
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setStaffType(Integer staffType) {
        this.staffType = staffType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property_staff.duty
     *
     * @return the value of sc_property_staff.duty
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property_staff.duty
     *
     * @param duty the value for sc_property_staff.duty
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property_staff.create_time
     *
     * @return the value of sc_property_staff.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property_staff.create_time
     *
     * @param createTime the value for sc_property_staff.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property_staff.creator_id
     *
     * @return the value of sc_property_staff.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property_staff.creator_id
     *
     * @param creatorId the value for sc_property_staff.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_property_staff.modify_time
     *
     * @return the value of sc_property_staff.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_property_staff.modify_time
     *
     * @param modifyTime the value for sc_property_staff.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}