package com.sct.service.database.entity;

import java.io.Serializable;
import java.util.Date;

public class ScRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_role.id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_role.role_name
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_role.role_type
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private Boolean roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_role.create_time
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_role.creator_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_role.modify_time
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_role.comment
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_role.grid_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private Integer gridId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_role.grid_level
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private Boolean gridLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_role
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_role.id
     *
     * @return the value of sc_role.id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_role.id
     *
     * @param id the value for sc_role.id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_role.role_name
     *
     * @return the value of sc_role.role_name
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_role.role_name
     *
     * @param roleName the value for sc_role.role_name
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_role.role_type
     *
     * @return the value of sc_role.role_type
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public Boolean getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_role.role_type
     *
     * @param roleType the value for sc_role.role_type
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setRoleType(Boolean roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_role.create_time
     *
     * @return the value of sc_role.create_time
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_role.create_time
     *
     * @param createTime the value for sc_role.create_time
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_role.creator_id
     *
     * @return the value of sc_role.creator_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_role.creator_id
     *
     * @param creatorId the value for sc_role.creator_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_role.modify_time
     *
     * @return the value of sc_role.modify_time
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_role.modify_time
     *
     * @param modifyTime the value for sc_role.modify_time
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_role.comment
     *
     * @return the value of sc_role.comment
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_role.comment
     *
     * @param comment the value for sc_role.comment
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_role.grid_id
     *
     * @return the value of sc_role.grid_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public Integer getGridId() {
        return gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_role.grid_id
     *
     * @param gridId the value for sc_role.grid_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setGridId(Integer gridId) {
        this.gridId = gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_role.grid_level
     *
     * @return the value of sc_role.grid_level
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public Boolean getGridLevel() {
        return gridLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_role.grid_level
     *
     * @param gridLevel the value for sc_role.grid_level
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setGridLevel(Boolean gridLevel) {
        this.gridLevel = gridLevel;
    }
}