package com.sct.service.database.entity;

import java.io.Serializable;

public class ScRoleOperations implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_role_operations.role_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_role_operations.dev_type
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private Boolean devType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_role_operations.oper_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private Integer operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_role_operations
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_role_operations.role_id
     *
     * @return the value of sc_role_operations.role_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_role_operations.role_id
     *
     * @param roleId the value for sc_role_operations.role_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_role_operations.dev_type
     *
     * @return the value of sc_role_operations.dev_type
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public Boolean getDevType() {
        return devType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_role_operations.dev_type
     *
     * @param devType the value for sc_role_operations.dev_type
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setDevType(Boolean devType) {
        this.devType = devType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_role_operations.oper_id
     *
     * @return the value of sc_role_operations.oper_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public Integer getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_role_operations.oper_id
     *
     * @param operId the value for sc_role_operations.oper_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setOperId(Integer operId) {
        this.operId = operId;
    }
}