package com.sct.service.database.entity;

import java.io.Serializable;
import java.util.Date;

public class ScSsoLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_sso_log.id
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_sso_log.user_id
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_sso_log.sso_log_type
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    private Integer ssoLogType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_sso_log.sso_service_id
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    private String ssoServiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_sso_log.create_time
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_sso_log.operation_status
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    private Integer operationStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_sso_log.operation_user_id
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    private String operationUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_sso_log.request_ip
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    private String requestIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_sso_log.request_user_agent
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    private String requestUserAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_sso_log.request_proxy
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    private String requestProxy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_sso_log.request_imei
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    private String requestImei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_sso_log
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_sso_log.id
     *
     * @return the value of sc_sso_log.id
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_sso_log.id
     *
     * @param id the value for sc_sso_log.id
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_sso_log.user_id
     *
     * @return the value of sc_sso_log.user_id
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_sso_log.user_id
     *
     * @param userId the value for sc_sso_log.user_id
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_sso_log.sso_log_type
     *
     * @return the value of sc_sso_log.sso_log_type
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public Integer getSsoLogType() {
        return ssoLogType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_sso_log.sso_log_type
     *
     * @param ssoLogType the value for sc_sso_log.sso_log_type
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public void setSsoLogType(Integer ssoLogType) {
        this.ssoLogType = ssoLogType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_sso_log.sso_service_id
     *
     * @return the value of sc_sso_log.sso_service_id
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public String getSsoServiceId() {
        return ssoServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_sso_log.sso_service_id
     *
     * @param ssoServiceId the value for sc_sso_log.sso_service_id
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public void setSsoServiceId(String ssoServiceId) {
        this.ssoServiceId = ssoServiceId == null ? null : ssoServiceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_sso_log.create_time
     *
     * @return the value of sc_sso_log.create_time
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_sso_log.create_time
     *
     * @param createTime the value for sc_sso_log.create_time
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_sso_log.operation_status
     *
     * @return the value of sc_sso_log.operation_status
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public Integer getOperationStatus() {
        return operationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_sso_log.operation_status
     *
     * @param operationStatus the value for sc_sso_log.operation_status
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public void setOperationStatus(Integer operationStatus) {
        this.operationStatus = operationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_sso_log.operation_user_id
     *
     * @return the value of sc_sso_log.operation_user_id
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public String getOperationUserId() {
        return operationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_sso_log.operation_user_id
     *
     * @param operationUserId the value for sc_sso_log.operation_user_id
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public void setOperationUserId(String operationUserId) {
        this.operationUserId = operationUserId == null ? null : operationUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_sso_log.request_ip
     *
     * @return the value of sc_sso_log.request_ip
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public String getRequestIp() {
        return requestIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_sso_log.request_ip
     *
     * @param requestIp the value for sc_sso_log.request_ip
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp == null ? null : requestIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_sso_log.request_user_agent
     *
     * @return the value of sc_sso_log.request_user_agent
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public String getRequestUserAgent() {
        return requestUserAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_sso_log.request_user_agent
     *
     * @param requestUserAgent the value for sc_sso_log.request_user_agent
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public void setRequestUserAgent(String requestUserAgent) {
        this.requestUserAgent = requestUserAgent == null ? null : requestUserAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_sso_log.request_proxy
     *
     * @return the value of sc_sso_log.request_proxy
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public String getRequestProxy() {
        return requestProxy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_sso_log.request_proxy
     *
     * @param requestProxy the value for sc_sso_log.request_proxy
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public void setRequestProxy(String requestProxy) {
        this.requestProxy = requestProxy == null ? null : requestProxy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_sso_log.request_imei
     *
     * @return the value of sc_sso_log.request_imei
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public String getRequestImei() {
        return requestImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_sso_log.request_imei
     *
     * @param requestImei the value for sc_sso_log.request_imei
     *
     * @mbg.generated Tue Jan 12 20:12:31 CST 2021
     */
    public void setRequestImei(String requestImei) {
        this.requestImei = requestImei == null ? null : requestImei.trim();
    }
}