package com.sct.service.database.entity;

import com.sct.service.database.extend.BaseExtend;

import java.io.Serializable;
import java.util.Date;

public class ScUserHouseRel extends BaseExtend implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_house_rel.user_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_house_rel.house_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer houseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_house_rel.owner_rel
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer ownerRel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_house_rel.valid_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date validTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_house_rel.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_house_rel.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_house_rel.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_user_house_rel
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_house_rel.user_id
     *
     * @return the value of sc_user_house_rel.user_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_house_rel.user_id
     *
     * @param userId the value for sc_user_house_rel.user_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_house_rel.house_id
     *
     * @return the value of sc_user_house_rel.house_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_house_rel.house_id
     *
     * @param houseId the value for sc_user_house_rel.house_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_house_rel.owner_rel
     *
     * @return the value of sc_user_house_rel.owner_rel
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getOwnerRel() {
        return ownerRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_house_rel.owner_rel
     *
     * @param ownerRel the value for sc_user_house_rel.owner_rel
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setOwnerRel(Integer ownerRel) {
        this.ownerRel = ownerRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_house_rel.valid_time
     *
     * @return the value of sc_user_house_rel.valid_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getValidTime() {
        return validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_house_rel.valid_time
     *
     * @param validTime the value for sc_user_house_rel.valid_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setValidTime(Date validTime) {
        this.validTime = validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_house_rel.create_time
     *
     * @return the value of sc_user_house_rel.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_house_rel.create_time
     *
     * @param createTime the value for sc_user_house_rel.create_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_house_rel.creator_id
     *
     * @return the value of sc_user_house_rel.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_house_rel.creator_id
     *
     * @param creatorId the value for sc_user_house_rel.creator_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_house_rel.modify_time
     *
     * @return the value of sc_user_house_rel.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_house_rel.modify_time
     *
     * @param modifyTime the value for sc_user_house_rel.modify_time
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}