package com.sct.service.database.entity;

import java.io.Serializable;

public class ScUserRoleRel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_role_rel.user_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_role_rel.role_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_role_rel.role_type
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Boolean roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_user_role_rel
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_role_rel.user_id
     *
     * @return the value of sc_user_role_rel.user_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_role_rel.user_id
     *
     * @param userId the value for sc_user_role_rel.user_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_role_rel.role_id
     *
     * @return the value of sc_user_role_rel.role_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_role_rel.role_id
     *
     * @param roleId the value for sc_user_role_rel.role_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_role_rel.role_type
     *
     * @return the value of sc_user_role_rel.role_type
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Boolean getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_role_rel.role_type
     *
     * @param roleType the value for sc_user_role_rel.role_type
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setRoleType(Boolean roleType) {
        this.roleType = roleType;
    }
}