package com.sct.service.database.entity;

import java.io.Serializable;

public class ScUserRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_role.user_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_role.role_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_role.role_type
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private Boolean roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_user_role
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_role.user_id
     *
     * @return the value of sc_user_role.user_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_role.user_id
     *
     * @param userId the value for sc_user_role.user_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_role.role_id
     *
     * @return the value of sc_user_role.role_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_role.role_id
     *
     * @param roleId the value for sc_user_role.role_id
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_role.role_type
     *
     * @return the value of sc_user_role.role_type
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public Boolean getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_role.role_type
     *
     * @param roleType the value for sc_user_role.role_type
     *
     * @mbg.generated Sat Nov 28 16:00:48 CST 2020
     */
    public void setRoleType(Boolean roleType) {
        this.roleType = roleType;
    }
}