package com.sct.service.database.entity;

import java.io.Serializable;

public class ScZone implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_zone.province_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_zone.province_name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_zone.city_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_zone.city_name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_zone.county_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private Integer countyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_zone.county_name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private String countyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_zone
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_zone.province_id
     *
     * @return the value of sc_zone.province_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_zone.province_id
     *
     * @param provinceId the value for sc_zone.province_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_zone.province_name
     *
     * @return the value of sc_zone.province_name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_zone.province_name
     *
     * @param provinceName the value for sc_zone.province_name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_zone.city_id
     *
     * @return the value of sc_zone.city_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_zone.city_id
     *
     * @param cityId the value for sc_zone.city_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_zone.city_name
     *
     * @return the value of sc_zone.city_name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_zone.city_name
     *
     * @param cityName the value for sc_zone.city_name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_zone.county_id
     *
     * @return the value of sc_zone.county_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public Integer getCountyId() {
        return countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_zone.county_id
     *
     * @param countyId the value for sc_zone.county_id
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCountyId(Integer countyId) {
        this.countyId = countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_zone.county_name
     *
     * @return the value of sc_zone.county_name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public String getCountyName() {
        return countyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_zone.county_name
     *
     * @param countyName the value for sc_zone.county_name
     *
     * @mbg.generated Tue Feb 16 11:09:04 CST 2021
     */
    public void setCountyName(String countyName) {
        this.countyName = countyName == null ? null : countyName.trim();
    }
}