server:
  servlet:
    session:
      timeout: PT12H
  compression:
    enabled: true
    min-response-size: 1024

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG

sms:
  url: ''
  user-account: ''
  password: ''
  ecname: ''